
//Daily Challenge : Guess The Number
/*
* @author: N'goran Kouadio Jean Cyrille
* @description:Create a guess the number game that allows the user to guess 
* the number generated by the computer between 1 to 100.
* date: 04/02/2023
*/

package dailychallenge;

import java.util.Random;
import java.util.Scanner;

public class Guess {
	public static void main(String[] args) {
		// declaration part
		int targetNumber, guess;
		int attempts = 0;
		try (Scanner sc = new Scanner(System.in)) {
			// random a number
			Random rand = new Random();
			targetNumber = rand.nextInt(100) + 1;
			attempts = 0;
			// user input a number
			System.out.print("Guess the number (1 - 100): ");

			// do while to iterate the number of chance
			do {
				guess = sc.nextInt();
				attempts++;
				// Conditions to check if the user guess the random number
				if (guess > targetNumber) {
					System.out.println("Number is too small!");
					System.out.println("you can enter a new number");
				} else if (guess < targetNumber) {
					System.out.println("Number is too great!");
					System.out.println("you can enter a new number");
				}
			} while (guess != targetNumber && attempts < 3);
			if (guess == targetNumber) {
				System.out.println("Congratulations! you guess the number in  " + attempts + " tentatives.");
			} else {
				System.out.println("You lose! The number was " + targetNumber);
			}
		}
	}
}
